- name: Fix the home directories of NFS users
  hosts: all
  become: yes
  tasks:
    - name: Make some bash scripting...
      community.general.snap:
        name: system
        options: homedirs=/nfs/home
      become_method: sudo
      become_user: root
